/**
 * @fileoverview Root layout component for the Next.js application
 * @author Offer Hub Team
 */

import './globals.css';

import { Geist, Geist_Mono } from 'next/font/google';

import { EscrowProvider } from '@/providers/scrow.provider';
import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import { TrustlessWorkProvider } from '@/providers/TrustlessWorkProvider';
import { WalletProvider } from '@/components/onboarding/WalletContext';
import ErrorBoundary from '@/components/shared/ErrorBoundary';
import { NotificationProvider } from '@/lib/contexts/NotificatonContext';
import { TalentProvider } from '@/lib/contexts/TalentContext';
import { OfferProvider } from '@/lib/contexts/OfferContext';
import { Suspense } from 'react';
import NotificationToast from '@/components/shared/NotificationToast';
import { MessageProvider } from '@/lib/contexts/MessageContext';
import { KeyboardShortcutsProvider } from '@/components/common/keyboard-shortcuts-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TrustlessWorkProvider>
          <ErrorBoundary>
            <NotificationProvider>
              <TalentProvider>
                <MessageProvider>
                  <OfferProvider>
                    <WalletProvider>
                      <EscrowProvider>
                        <KeyboardShortcutsProvider>
                          <Suspense fallback={null}>
                            <main>
                              {children}
                            </main>
                            <NotificationToast />
                          </Suspense>
                          <Toaster position="top-right" />
                        </KeyboardShortcutsProvider>
                      </EscrowProvider>
                    </WalletProvider>
                  </OfferProvider>
                </MessageProvider>
              </TalentProvider>
            </NotificationProvider>
          </ErrorBoundary>
        </TrustlessWorkProvider>
      </body>
    </html>
  );
}
