import Header from '@/components/client-dashboard/Header';
import { ClientSidebar } from '@/components/client-dashboard/Sidebar';
import { Metadata } from 'next';


export const metadata: Metadata = {
    title: 'Offer-Hub Talent Page',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main>
            <Header />
            <section className='flex pt-16'>
                <ClientSidebar />

                <div className='flex-1'>
                    {children}
                </div>
            </section>
        </main>
    );
}
